Algoritmo "antecessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Alisson da Silva Dutra
// Data atual  : 14/03/2024
Var
num,antecessor:inteiro

Inicio
     Escreval("Digite um numero")
     leia(num)
     antecessor <- num - 1
     Escreva ("Antecessor,", num, " é ", antecessor)

Fimalgoritmo