Algoritmo "calcular_volumeLata"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Alisson Dutra
// Data atual  : 18/03/2024
Var
   raioLata:real
   alturaLata:real
   volumeLata:real

Inicio
       escreva("informe o raio da lata: ")
       leia(raioLata)
       escreva ("Informe a altura da lata: ")
       leia(alturaLata)
       volumeLata <- 3,14 * raioLata ^ 2 * alturaLata
       Escreva ("o volume da lata é: ", volumeLata)



Fimalgoritmo