Algoritmo "ConversorTemperatura_exercicio12"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Alisson Dutra
// Data atual  : 18/03/2024
Var
   fahrenheit, celsius: real


Inicio
      Escreval ("Digite a temperatura em fahrenheit: ")
      leia(fahrenheit)
      
      celsius <- (fahrenheit - 32) * 5 / 9
      
      Escreva("a temperatura é: ", celsius)

Fimalgoritmo