Algoritmo "AreaRetangulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Alisson da Silva Dutra
// Data atual  : 14/03/2024
Var
base:real
altura:real
area:real


Inicio
     Escreval("coloque um valor para base")
     leia(base)
     Escreval("coloque um valor para altura")
     leia(altura)
     area <- base * altura
     Escreva("a area do seu retangulo e", area)


Fimalgoritmo