Algoritmo "MANZANO_PAG41_EX4_B"
// Disciplina   : Lógica de Programação com JavaScript
// Professor   : Jailson Costa
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/04/2024
Var

   valor:inteiro

Inicio
   Escreval ("Digite um valor")
   leia(valor)

   se valor < 0 entao
      valor<- valor * -1
   senao
      valor<- valor

   fimse

   Escreval ("O valor absoluto é: ",valor)

Fimalgoritmo