Algoritmo "multiplicação"
// Disciplina   : [Linguagem e Lógica com JavaScript]
// Professor   : Jailson
// Descrição   : multiplicação
// Autor(a)    : Alisson da Silva Dutra
// Data atual  : 11/03/2024
Var
// Seção de Declarações das variáveis
n1,n2,multiplicacao:inteiro

Inicio
      Escreval("Digite um número: ")
      leia(n1)
      Escreval("Digite outro número: ")
      leia(n2)
      multiplicacao <- n1 * n2
      Escreval ("O resultado da multiplicacao é: ", multiplicacao)




Fimalgoritmo