Algoritmo "Quadrado_da_Diferenca"
// Professor   : Jailson Costa
// Descrição   : calcula a diferença entre A e B
// Autor(a)    : Alisson Dutra
// Data atual  : 20/03/2024
Var
A,B, diferenca , quadrado_diferenca:inteiro

Inicio
Escreva ("Digite o valor de A: ")
leia (A)
Escreva ("Digite o valor de B: ")
leia (B)

diferenca <- A - B
quadrado_diferenca <- A * B

Escreval ("O quadrado da diferença entre ", A , " e " , B, " é ", quadrado_diferenca)
Fimalgoritmo