Algoritmo "verifica_maior_10"
// Disciplina   : Lógica de Programação com JavaScript
// Professor   : Jailson Costa
// Descrição   : verifica se o número é maior que 10
// Autor(a)    : Alisson Dutra
// Data atual  : 28/03/2024
Var

   numero:real

Inicio
   Escreval ("Escreva um número: ")
   leia (numero)
   se numero>= 0 entao
      Escreval ("Número é positivo! ")
   senao
      Escreval ("Número é negativo! ")
   fimse


Fimalgoritmo